### ISSUE TITLE
v0.1.2 无法查找任何小说

### ISSUE THREAD

**Issue by bbblucky** [howie6879/NIYT#2]
尝试了各种书名，均显示下面的错误

> $ 请输入小说名~ 圣墟
Error: Get /s?q=%E5%9C%A3%E5%A2%9F+%E5%B0%8F%E8%AF%B4+%E6%9C%80%E6%96%B0%E7%AB%A0%E8%8A%82&ie=utf-8: stopped after 10 redirects
暂无结果，请重试！

**Comment by howie6879** [comment]
建议检查下网络：
![image](https://user-images.githubusercontent.com/17047388/40209873-833594b8-5a74-11e8-9767-444884a009a7.png)

**Comment by bbblucky** [comment]
请问是用哪个网站进行搜索的呢？我想测试下是不是无法连接搜索网站

**Comment by howie6879** [comment]
360
