### ISSUE TITLE
如何从第一章开始看？

### ISSUE THREAD

**Issue by qingfeng** [howie6879/NIYT#3]
感谢

**Comment by howie6879** [comment]
抱歉 NIYT目的就是追书 不支持从第一章开始看 可以考虑 https://github.com/howie6879/owllook

**Comment by qingfeng** [comment]
> 抱歉 NIYT目的就是追书 不支持从第一章开始看 可以考虑 https://github.com/howie6879/owllook

感谢推荐

**Comment by ch4rc0al1080** [comment]
令人遗憾
